trigger:
- main

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  displayName: 'Build, Test, and Run GitLeaks'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals DESKTOP-1QUEN13

  steps:
  # Step to checkout the code
  - checkout: self

  # Step to set JAVA_HOME and MAVEN_HOME using a batch file
  - script: |
      echo @echo off > setup_env.bat
      echo set MAVEN_HOME=C:\Program Files\apache-maven-3.9.9 >> setup_env.bat
      echo set JAVA_HOME=C:\Program Files\Java\jdk-17 >> setup_env.bat
      echo set PATH=%MAVEN_HOME%\bin;%%PATH%% >> setup_env.bat
      echo call mvn clean install >> setup_env.bat
      call setup_env.bat
    displayName: 'Setup Environment and Build'

  # Step to verify environment variables
  - script: |
      echo JAVA_HOME: %JAVA_HOME%
      echo MAVEN_HOME: %MAVEN_HOME%
      echo PATH: %PATH%
      mvn -version
    displayName: 'Verify Maven and Java Installation'

  # Step to run tests
  - script: mvn test
    displayName: 'Run unit tests'

  # Step to run GitLeaks
  - powershell: |
      Invoke-WebRequest -Uri "https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-windows-amd64.exe" -OutFile "gitleaks.exe"
      .\gitleaks.exe --path=. --report=report.json
    displayName: 'Run GitLeaks'

  # Optional: Publish GitLeaks report as a build artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'report.json'
      ArtifactName: 'gitleaks-report'
      publishLocation: 'Container'
