trigger:
- main

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  displayName: 'Build, Test, and Run GitLeaks'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals DESKTOP-IGD4N6V

  steps:
  # Step to checkout the code
  - checkout: self

  # Step to set the JAVA_HOME environment variable
  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17.0.2"
      echo "JAVA_HOME is set to %JAVA_HOME%"
    displayName: 'Set JAVA_HOME'

  # Step to run Maven build
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\Program Files\Java\jdk-17.0.2'  # This should point to the JDK directory, not bin
      mavenVersionOption: 'Path'
      mavenDirectory: 'C:\Program Files\apache-maven-3.9.6'  # This should point to the Maven directory, not bin
      mavenSetM2Home: true
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      goals: 'clean install'  # Specify the Maven goals here

  # Step to run unit tests
  - script: mvn test
    displayName: 'Run unit tests'

  - task: Gitleaks@2
    inputs:
      scanlocation: '$(Build.SourcesDirectory)'
      configtype: 'predefined'
      predefinedconfigfile: 'UDMSecretChecksv8.toml'
      reportformat: 'json'
