trigger:
- main

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  displayName: 'Build, Test, and Run GitLeaks'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals DESKTOP-IGD4N6V

  steps:
  # Step to checkout the code
  - checkout: self

  # Step to set the JAVA_HOME environment variable
  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17.0.2"
      echo "JAVA_HOME is set to %JAVA_HOME%"
    displayName: 'Set JAVA_HOME'

  # Step to run Maven build
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\Program Files\Java\jdk-17.0.2'
      mavenVersionOption: 'Path'
      mavenDirectory: 'C:\Program Files\apache-maven-3.9.6'
      mavenSetM2Home: true
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
      goals: 'clean install'

  # Step to run unit tests
  - script: mvn test
    displayName: 'Run unit tests'

  # Step to run Gitleaks
  - task: Gitleaks@2
    inputs:
      scanlocation: '$(Build.SourcesDirectory)'
      configtype: 'predefined'
      predefinedconfigfile: 'UDMSecretChecksv8.toml'
      reportformat: 'json'
      outputfile: '$(Build.ArtifactStagingDirectory)/gitleaks-report.json'

  # Step to publish the Gitleaks report
  - publish: 'D:/agent/vsts-agent-win-x64-3.245.0/_work/1/s/gitleaks-report.json'
    artifact: gitleaks-report
    displayName: 'Publish Gitleaks Report'
