trigger:
- main

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  displayName: 'Build, Test, and Run GitLeaks'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals DESKTOP-1QUEN13

  steps:
  # Step to checkout the code
  - checkout: self

  # Step to set the JAVA_HOME environment variable (if needed)
  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
      echo "JAVA_HOME is set to %JAVA_HOME%"
    displayName: 'Set JAVA_HOME'


  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'Path'
      jdkDirectory: 'C:\Program Files\Java\jdk-17'
      mavenVersionOption: 'Path'
      mavenDirectory: 'C:\Program Files\apache-maven-3.9.9'
      mavenSetM2Home: true
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - script: mvn -version
    displayName: 'Check Maven Version'

  # - script: mvn clean install
  #   displayName: 'Build the project'

  # # Step to run tests
  # - script: mvn test
  #   displayName: 'Run unit tests'

  # # Step to run GitLeaks
  # - powershell: |
  #     Invoke-WebRequest -Uri "https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-windows-amd64.exe" -OutFile "gitleaks.exe"
  #     .\gitleaks.exe --path=. --report=report.json
  #   displayName: 'Run GitLeaks'

  # # Optional: Publish GitLeaks report as a build artifact
  # - task: PublishBuildArtifacts@1
  #   inputs:
  #     PathtoPublish: 'report.json'
  #     ArtifactName: 'gitleaks-report'
  #     publishLocation: 'Container'
