trigger:
- main

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  displayName: 'Build, Test, and Run GitLeaks'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals DESKTOP-1QUEN13

  steps:
  # Step to checkout the code
  - checkout: self

  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
      echo "JAVA_HOME is set to %JAVA_HOME%"
    displayName: 'Set JAVA_HOME'

  - task: Maven@4
    inputs:
      azureSubscription: 'Free Trial(b92e97c1-b96e-49cf-88e2-821cb18fc022)'
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - script: mvn -version
    displayName: 'Check Maven Version'