trigger:
- main

pool:
  name: 'Default'

jobs:
- job: BuildAndTest
  displayName: 'Build, Test, and Run GitLeaks'
  pool:
    name: 'Default'
    demands:
      - agent.name -equals DESKTOP-1QUEN13

  steps:
  # Step to checkout the code
  - checkout: self

  # Step to set JAVA_HOME and MAVEN_HOME
  - script: |
      echo "##vso[task.setvariable variable=JAVA_HOME]C:\Program Files\Java\jdk-17"
      echo "##vso[task.setvariable variable=MAVEN_HOME]C:\Program Files\apache-maven-3.9.9"
      echo "##vso[task.setvariable variable=PATH]$MAVEN_HOME\bin;%PATH%"
      echo "JAVA_HOME is set to %JAVA_HOME%"
      echo "MAVEN_HOME is set to %MAVEN_HOME%"
      echo "Updated PATH is %PATH%"
    displayName: 'Set JAVA_HOME and MAVEN_HOME'

  # Step to build the project using Maven
  - task: MavenAuthenticate@0
    inputs:
      mavenVersionOption: 'MavenVersion'
      mavenVersion: '3.6.3'  # Specify your Maven version

  - script: mvn clean install
    displayName: 'Build the project'

  # Step to run tests
  - script: mvn test
    displayName: 'Run unit tests'

  # Step to run GitLeaks
  - powershell: |
      Invoke-WebRequest -Uri "https://github.com/zricethezav/gitleaks/releases/latest/download/gitleaks-windows-amd64.exe" -OutFile "gitleaks.exe"
      .\gitleaks.exe --path=. --report=report.json
    displayName: 'Run GitLeaks'

  # Optional: Publish GitLeaks report as a build artifact
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'report.json'
      ArtifactName: 'gitleaks-report'
      publishLocation: 'Container'
